[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.install]
cmds = ["npm ci"]
# Explicitly force cacheDirectories to empty to override default behavior
cacheDirectories = []

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
# Explicitly force cacheDirectories to empty here too
cacheDirectories = []

[start]
cmd = "npm run start"
