[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build"]
# Completely disabled caching directories to avoid EBUSY/lock errors
# cacheDirectories = [".next/cache", "node_modules/.cache"]

[start]
cmd = "npm run start"
